create table
  public.cart_customers (
    id bigint generated by default as identity,
    customer text not null,
    constraint cart_customers_pkey primary key (id, customer)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint not null,
    item_sku text not null,
    quantity bigint not null,
    constraint unique_cart_item unique (id, item_sku)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    num_red_ml integer not null,
    gold integer not null,
    num_blue_ml integer not null default 0,
    num_green_ml integer not null default 0
  ) tablespace pg_default;

  create table
  public.potions (
    item_sku text not null,
    red_amount bigint not null default '0'::bigint,
    blue_amount bigint not null default '0'::bigint,
    green_amount bigint not null default '0'::bigint,
    dark_amount bigint not null default '0'::bigint,
    cost bigint not null default '0'::bigint,
    num_potion bigint not null default '0'::bigint,
    constraint potions_pkey primary key (item_sku)
  ) tablespace pg_default;