create table
  public.cart_customers (
    id bigint generated by default as identity,
    customer text not null,
    constraint cart_customers_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint not null,
    item_sku text not null,
    quantity bigint not null,
    constraint unique_cart_item unique (id, item_sku),
    constraint cart_items_id_fkey foreign key (id) references cart_customers (id),
    constraint cart_items_item_sku_fkey foreign key (item_sku) references potions (item_sku)
  ) tablespace pg_default;

  create table
  public.potions (
    item_sku text not null,
    red_amount integer not null default 0,
    blue_amount integer not null default 0,
    green_amount integer not null default 0,
    dark_amount integer not null default 0,
    cost integer not null default 0,
    constraint potions_pkey primary key (item_sku)
  ) tablespace pg_default;

  create table
  public.transactions (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    description text not null,
    type text not null,
    constraint transactions_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.customer_ledger_entries (
    id bigint generated by default as identity,
    customer_id bigint not null,
    transaction_id bigint not null,
    change_gold integer not null default 0,
    item_sku text not null,
    change_potions integer not null,
    constraint customer_transactions_pkey primary key (id),
    constraint customer_ledger_entries_customer_id_fkey foreign key (customer_id) references cart_customers (id),
    constraint customer_ledger_entries_item_sku_fkey foreign key (item_sku) references potions (item_sku),
    constraint customer_ledger_entries_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

create table
  public.inventory_ledger_entries (
    id bigint generated by default as identity,
    transaction_id bigint not null,
    change_gold integer not null default 0,
    change_red integer not null default 0,
    change_blue integer not null default 0,
    change_green integer not null default 0,
    constraint inventory_ledger_entries _pkey primary key (id),
    constraint inventory_ledger_entries_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;

  create table
  public.potion_ledger_entries (
    id bigint generated by default as identity,
    transaction_id bigint not null,
    item_sku text not null,
    change_potions integer not null default 0,
    change_red integer not null default 0,
    change_green integer not null default 0,
    change_blue integer not null default 0,
    constraint potion_ledger_entries _pkey primary key (id),
    constraint potion_ledger_entries_item_sku_fkey foreign key (item_sku) references potions (item_sku),
    constraint potion_ledger_entries_transaction_id_fkey foreign key (transaction_id) references transactions (id)
  ) tablespace pg_default;